server:
  port: @comment.service.port@
spring:
  application:
    name: comment-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  redis:
    host: localhost
    port: 6379
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_comment?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis:
  type-aliases-package: com.phantom.commentservice
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: pageNum=pageNum,pageSize=pageSize
  row-bounds-with-count: true