server:
  port: @user.service.port@

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_user?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  redis:
    host: localhost
    port: 6379

mybatis:
  type-aliases-package: com.phantom.userservice.bean.po
  configuration:
    use-underscore-to-camel-case: true

jwt:
  secret: 4e7d3c8c804c94b087dbf95d88e25d2d8e0817fdfefb7c9b5b00e7c03c387e34
  expiration: 86400000

logging:
  level:
    com.alibaba.nacos: INFO
    org.springframework.cloud: INFO

